---
- hosts: all
  gather_facts: no
  vars:
    #regcode: "YOU HAVE TO GIVE YOUR OWN. Uncomment and define yours."
  tasks:
    - name: Register sle
      command: "SUSEConnect -r {{ regcode }}"
    - name: Register sle module containers
      command: "SUSEConnect -p sle-module-containers/15.1/x86_64 -r {{regcode }}"
